<?php
/**
 * Template Name: CV
 * Template Post Type: page
 *
 * @package Morten_Portfolio
 */
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}
?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php wp_head(); ?>
</head>
<body <?php body_class( 'cv-page' ); ?>>
<?php wp_body_open(); ?>
<?php while ( have_posts() ) : the_post(); ?>
<?php
$cv_viewer_name = function_exists( 'mca_cv_current_viewer_name' )
    ? mca_cv_current_viewer_name()
    : '';
?>
<main class="cv-shell cv-style-<?php echo esc_attr( morten_cv_style() ); ?>" data-cv-style="<?php echo esc_attr( morten_cv_style() ); ?>" data-cv-language="<?php echo esc_attr( morten_cv_language() ); ?>" data-cv-viewer="<?php echo esc_attr( $cv_viewer_name ); ?>">
    <header class="cv-topbar">
        <a class="cv-brand" href="<?php echo esc_url( home_url( '/' ) ); ?>">
            <span class="cv-brand-mark">MH</span>
            <span><?php echo esc_html( morten_portfolio_cv_get_settings()['name'] ); ?></span>
        </a>
        <div class="cv-topbar-right">
            <?php if ( $cv_viewer_name ) : ?>
                <div class="cv-viewer" aria-label="Innlogget bruker">
                    <span class="cv-viewer-label">Innlogget som</span>
                    <strong><?php echo esc_html( $cv_viewer_name ); ?></strong>
                </div>
            <?php endif; ?>
            <?php if ( morten_cv_multilingual_enabled() ) : ?><nav class="cv-language-switch" aria-label="Språk"><a class="cv-lang-link<?php echo morten_cv_is_english() ? '' : ' is-active'; ?>" href="<?php echo esc_url( morten_cv_url( 'no' ) ); ?>">NO</a><a class="cv-lang-link<?php echo morten_cv_is_english() ? ' is-active' : ''; ?>" href="<?php echo esc_url( morten_cv_url( 'en' ) ); ?>">EN</a></nav><?php endif; ?><div class="cv-actions">
                <button type="button" class="cv-action-btn primary" id="pdfButton"><?php echo esc_html( morten_cv_label( 'Lagre som PDF', 'Save as PDF' ) ); ?></button>
                <?php if ( function_exists( 'mca_cv_is_admin_bypass' ) && mca_cv_is_admin_bypass() ) : ?>
                    <span class="cv-action-btn is-disabled" aria-disabled="true" title="Administratorer har automatisk tilgang"><?php echo esc_html( morten_cv_label( 'Logg ut', 'Log out' ) ); ?></span>
                <?php elseif ( function_exists( 'mca_cv_logout_url' ) && mca_cv_logout_url() ) : ?>
                    <a class="cv-action-btn" href="<?php echo esc_url( mca_cv_logout_url() ); ?>"><?php echo esc_html( morten_cv_label( 'Logg ut', 'Log out' ) ); ?></a>
                <?php endif; ?>
                <a class="cv-action-btn" href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php echo esc_html( morten_cv_label( 'Til forsiden', 'To frontpage' ) ); ?></a>
            </div>
        </div>
    </header>

    <article class="cv-document">
        <?php get_template_part( 'template-parts/cv/sidebar' ); ?>
        <?php get_template_part( 'template-parts/cv/main' ); ?>
    </article>
    <footer class="cv-pdf-footer" aria-hidden="true">
        <span><?php echo esc_html( morten_cv_label( 'Generert av', 'Generated by' ) ); ?> <strong id="cvPdfViewer"><?php echo esc_html( $cv_viewer_name ?: 'Ukjent bruker' ); ?></strong></span>
        <span id="cvPdfTimestamp"></span>
    </footer>
</main>
<?php endwhile; ?>
<?php wp_footer(); ?>
</body>
</html>
